name: Wake Render Server
on: 
  schedule:
    - cron: '*/10 3-4 * * *'
      timezone: 'America/Chicago'
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        run: curl https://dopa-ke7w.onrender.com/api/ping
  
